### ISSUE TITLE
sortable => no smart labels

### ISSUE THREAD

**Issue by pjscott** [bigpresh/Dancer-Plugin-SimpleCRUD#43] opened 2014-04-18 01:36 UTC
FYI, turning on sortable means that the smart column name translations no longer happen.

**Comment by joshrabinowitz** [comment] 2016-09-08 15:59
I think this has been fixed @bigpresh @pjscott

**Comment by bigpresh** [comment] 2017-05-21 22:50
Very, very belatedly, yes, I can confirm that this has since been fixed - just tried it in the example app with 1.13.

At a quick glance, it appears to have been fixed by @joshrabinowitz in 06e3b39e2b463785dc4cfdc89fccf8b3663c3808

**Closed by bigpresh** 2017-05-21 22:50 UTC
